### ISSUE TITLE
Add accessibility tags to widgets

### ISSUE THREAD

**Issue by pulkitm1999** [Hap-Map/HapMap#22]
Test it with voice-over

**Comment by emilychang9** [comment]
Use Semantics widgets to add labels to widgets (if labels are not already a property): https://medium.flutterdevs.com/semantics-widgets-in-flutter-4d7410a9d246

**Comment by emilychang9** [comment]
**MISSING LABELS**

Search Page:
- Help button (label should be "Help")
- Dictation button (label should be "Speak")
- Settings button (label should be "Settings")
- Suggestions (should be a group with label "Search suggestions", and each item inside should have its own label matching its text)

**Comment by emilychang9** [comment]
**MISSING LABELS**

Confirmation Page: 
N/A

Navigation Page:

- Should group text that is on the card so it can be read all at once (user can still enter the group to go through each text individually)
- Haptic Touch button missing label (label should be "Keep finger on the screen for haptic feedback")

**Comment by SimonaLiao** [comment]
> **MISSING LABELS**
> 
> Search Page:
> 
> * Help button (label should be "Help")
> * Dictation button (label should be "Speak")
> * Settings button (label should be "Settings")
> * Suggestions (should be a group with label "Search suggestions", and each item inside should have its own label matching its text)

added labels for buttons, but can't group all the suggestions yet (tried mergeSemantics, it's not working. added "search suggestion" label for each list item)

**Comment by SimonaLiao** [comment]
> **MISSING LABELS**
> 
> Confirmation Page: N/A
> 
> Navigation Page:
> 
> * Should group text that is on the card so it can be read all at once (user can still enter the group to go through each text individually)
> * Haptic Touch button missing label (label should be "Keep finger on the screen for haptic feedback")

grouped the text and added missing label
