### ISSUE TITLE
unable to search

### ISSUE THREAD

**Issue by MagicPillowGM** [Hap-Map/HapMap#95]
**Describe the bug**
I build and ran the app on an ios simulator.
I typed and selected a location, but once I click on the selected location on the search suggestion area, it enter a screen that reporting a error that:
`type "Null" is not a subtype of type "Position" `

**Comment by emilychang9** [comment]
Hi! We haven't run into that error message before while running HapMap. Do you have any screenshots of the error? Do you remember if your API key included the Google Directions and Places APIs? We'll discuss this during our project meeting on Thursday!

**Comment by emilychang9** [comment]
Closing since this issue should be solved in final release.
