### ISSUE TITLE
App Store/Google Play Store link

### ISSUE THREAD

**Issue by leftl** [Hap-Map/HapMap#96]
Hi all,
I noticed in the user documentation that this application is available in the Google Play Store and App Store but I've had a hard time finding it. Do you have links for the listing on either platform?

**Comment by emilychang9** [comment]
Hi, HapMap is not currently available on any app stores. We will update the user documentation to account for this! For now, the best way to try out HapMap is by following the build/run directions on the README file.

**Comment by emilychang9** [comment]
Closing for now while we work on the final release!
